### ISSUE TITLE
Conversion from Matrix{T} to Clifford{T} or Pauli{T} needs tolerances

### ISSUE THREAD

**Issue by marcusps** [BBN-Q/Cliffords.jl#24]
As it currently stands `convert()` does not take tolerances into account, but as the implementation makes clear, the routine depends on the tolerances to decide whether a complex matrix is near a Pauli/Clifford or not.  These tolerances will depend on how the matrix was generated, so assuming something based purely on `eps()` is not sufficient, and leads to breakage in some instances.

It is unclear to me if it is OK to augment the signature of `convert()` to take an optional argument for the tolerances, but that is what I'd propose.

**Comment by marcusps** [comment]
@blakejohnson I am looking for you guidance on how to address this in the Julia-way.

**Comment by jlapeyre** [comment]
Since you own `Pauli`, defining a method for `convert` with more arguments is not type squatting (or more precisely, number-of-argument squatting), so in this sense it's okay. Still, it's not clear whether optional arguments for tolerance fit  the semantics of `convert`.

There are two choices, adding a constructor or a method for `convert`. One test offered for whether `convert` makes sense is the following^1. When calling `push!(A, x)` and the type of `x` is not a subtype of the eltype of `A`, then `x` is automatically (generically) converted to the correct type, if an appropriate method can be found. So, if you want to support automatic conversion in cases like this, then defining a method for `convert` makes sense. Otherwise, use a constructor. But, there is no way to adjust the tolerance when `convert` is called by `push!`, etc. So, defining and using a constructor rather than `convert` appears to be the solution that best agrees with the semantics of both.

^1 https://discourse.julialang.org/t/convert-vs-constructors/4159/35,
https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Conversion-1

**Comment by marcusps** [comment]
So, @jlapeyre, maybe the right way to go about it is to define something like a `round` method, with parameterized tolerance, and let the user "round" the floating point matrices before converting to Cliffords?

**Comment by jlapeyre** [comment]
I would do the following. A user converts matrices to Paulis with a constructor, which is defined like this
```julia
function Pauli(m::AbstractMatrix; tolfac=eps(Float64))
    d = size(m,1)
    n = log(2,size(m,1))
    for p in allpaulis(n)
        overlap = tr(m*p) / d
        if isapprox(abs(overlap),1,atol = tolfac * d)
            return (round(real(overlap))+im*round(imag(overlap)))∘p
        elseif !isapprox(abs(overlap),0,atol=d*eps(Float64))
            error("Trying to convert non-Pauli matrix to a Pauli object")
        end
    end
end
```
So the user does `Pauli(m)` or `Pauli(m; tolfac=1e-13)`, etc.

Then `convert` would only be used when Julia performs an automatic conversion, eg inserting a matrix into an array of objects of type `Pauli`. (This might never occur in practice.) This method would be
```julia
function convert(::Type{Pauli{N}}, m::Matrix) where N
    return Pauli(m)
end
```
There is no tolerance here, because Julia's automatic conversion has no mechanism for supporting such a thing. We might want to omit the parameter `N`, or include another method.

**Comment by jlapeyre** [comment]
@marcusps, I think the following is a better solution. It doesn't require a tolerance. It just chooses the closest element.
```julia
function Pauli(m::AbstractMatrix)
    d = size(m,1)
    n = log(2,size(m,1))
    paulis = allpaulis(n)
    overlaps = [tr(m*p) / d for p in paulis]
    absoverlaps = [abs2(overlap) for overlap in overlaps]
    (_, index) = findmax(absoverlaps)
    phase_index = round(real(overlaps[index]))+im*round(imag(overlaps[index]))
    return phase_index ∘ paulis[index]
end
```
If the matrix is really noisy, then the `phase_index` won't be in the dictionary, and this will fail. One could add a check that `abs(phase_index)==1`.

(Also, there is a Julia package `ILog2`. It's much faster than `log(2,size(m,1))`. Not so important here, since the rest of the calculation is much more expensive. But, it's useful in general in quantum information code.)

**Comment by matthewware** [comment]
I believe this is taken care of now in #25.  @marcusps we can close this issue?

**Comment by marcusps** [comment]
Ah, indeed, just looking for the closest element is another option that
gets around all this. Thanks @jlapeyre & Matt!
